### ISSUE TITLE
Incomplete data being returned

### ISSUE THREAD

**Issue by melvinio16** [publichealthengland/coronavirus-dashboard-api-v2-server#5]
Hi, 

Calling the api for some metrics is not returning a complete data set, this is the case for both json and csv. It is cut off mid way through, not missing days. 

An example of one of the endpoints:

https://api.coronavirus.data.gov.uk/v2/data?areaType=ltla&format=json&metric=newCasesBySpecimenDateAgeDemographics

piping this into jq will give a validation error.

**Comment by xenatisch** [comment]
Where does it cut off? Is there a specific date or area?

**Comment by melvinio16** [comment]
No, just ends prematurely resulting in malformed json. looks like a size limit in the return.

**Comment by melvinio16** [comment]
Full set of failing metrics
ltla - none
msoa -
newTestsByPublishDate
plannedCapacityByPublishDate
newCasesBySpecimenDate
cumCasesBySpecimenDate
maleCases
femaleCases
cumAdmissionsByAge
newVirusTestsChange
newVirusTestsChangePercentage
newVirusTestsRollingSum
newVirusTestsRollingRate
newDeaths28DaysByDeathDateAgeDemographics
nation -
newTestsByPublishDate
plannedCapacityByPublishDate
newCasesBySpecimenDate
cumCasesBySpecimenDate
maleCases
femaleCases
cumAdmissionsByAge
femaleDeaths28Days
maleDeaths28Days
changeInNewCasesBySpecimenDate
newVirusTestsRollingRate
newDeaths28DaysByDeathDateAgeDemographics
newCasesBySpecimenDateAgeDemographics
uniqueCasePositivityBySpecimenDateRollingSum
uniquePeopleTestedBySpecimenDateRollingSum
nhs_region -
newTestsByPublishDate
plannedCapacityByPublishDate
newCasesBySpecimenDate
cumCasesBySpecimenDate
maleCases
femaleCases
cumAdmissionsByAge
femaleDeaths28Days
maleDeaths28Days
changeInNewCasesBySpecimenDate
newVirusTestsRollingRate
newDeaths28DaysByDeathDateAgeDemographics
newCasesBySpecimenDateAgeDemographics
uniqueCasePositivityBySpecimenDateRollingSum
uniquePeopleTestedBySpecimenDateRollingSum
nhs_trust-
newTestsByPublishDate
plannedCapacityByPublishDate
newCasesBySpecimenDate
cumCasesBySpecimenDate
maleCases
femaleCases
cumAdmissionsByAge
femaleDeaths28Days
maleDeaths28Days
newCasesByPublishDateRollingSum
newCasesByPublishDateRollingRate
newAdmissionsDirection
newAdmissionsChange
newAdmissionsChangePercentage
newAdmissionsRollingSum
newAdmissionsRollingRate
newDeaths28DaysByPublishDateDirection
newDeaths28DaysByPublishDateChange
newVirusTestsChangePercentage
newVirusTestsRollingSum
newVirusTestsRollingRate
newDeaths28DaysByDeathDateAgeDemographics
newCasesBySpecimenDateAgeDemographics
overview -
newTestsByPublishDate
plannedCapacityByPublishDate
newCasesBySpecimenDate
cumCasesBySpecimenDate
maleCases
femaleCases
cumAdmissionsByAge
femaleDeaths28Days
maleDeaths28Days
newVirusTestsRollingSum
newVirusTestsRollingRate
newDeaths28DaysByDeathDateAgeDemographics
newCasesBySpecimenDateAgeDemographics
uniqueCasePositivityBySpecimenDateRollingSum
region -
newTestsByPublishDate
plannedCapacityByPublishDate
newCasesBySpecimenDate
cumCasesBySpecimenDate
maleCases
femaleCases
cumAdmissionsByAge
femaleDeaths28Days
maleDeaths28Days
changeInNewCasesBySpecimenDate
previouslyReportedNewCasesBySpecimenDate
newDeaths28DaysByDeathDateAgeDemographics
newCasesBySpecimenDateAgeDemographics
uniqueCasePositivityBySpecimenDateRollingSum
uniquePeopleTestedBySpecimenDateRollingSum
utla -
newTestsByPublishDate
plannedCapacityByPublishDate
newCasesBySpecimenDate
cumCasesBySpecimenDate
maleCases
femaleCases
cumAdmissionsByAge
femaleDeaths28Days
maleDeaths28Days
changeInNewCasesBySpecimenDate
previouslyReportedNewCasesBySpecimenDate
newDeaths28DaysByDeathDateAgeDemographics
newCasesBySpecimenDateAgeDemographics
uniqueCasePositivityBySpecimenDateRollingSum
uniquePeopleTestedBySpecimenDateRollingSum
newPeopleReceivingFirstDose

**Comment by melvinio16** [comment]
Will work on getting a list together of any other failing metrics

**Comment by colic001** [comment]
The case age demographics by LTLA is the only one I have come across with the error, this is what happens to the JSON file in Power Query.

![image](https://user-images.githubusercontent.com/69187832/117454719-5abb7580-af3e-11eb-9371-d6dcd5ee9ed6.png)

As for the CSV version it misses of random LA's of such as Ashford

**Comment by xenatisch** [comment]
@melvinio16 It's unlikely to be related to metrics so much as it is related to the volume of the data being returned. 

I am disabling the streaming in favour of an alternative approach whereby instead of streaming and caching the data simultaneously, we first cache the in storage, then respond with a 303 redirect code against the cached file. This will reduce the chance of premature terminations. 

Additionally, I will be adding 2 new tags to the storage files - `in_progress` and `done`. When `in_progress=1` and `done=0`, the request will be held (suspended) with 10-second waiting periods. Once `in_progress=0` and `done=1`, the redirect code will be served. If `in_progress=0` and `done=0`, the cache item will be deleted to break any outstanding wait clause and induce a retry. 

The downside here is this approach:
- if the request fails frequently, you'll end up waiting for longer before getting failed request response
- you don't get a response until everything is ready

On the other hand, I expect this to improve consistency and reliability of the API.

Need to make some fine tuning and perform a few tests. Expect to deploy tonight. Will update here.

**Comment by xenatisch** [comment]
@colic001 As a part of [this update](https://github.com/publichealthengland/coronavirus-dashboard-api-v2-server/commit/ce1b5ad9fc7b2f346f03ee90c4c1437bdb5152e4), I've implemented a few safeguards to ensure that the beginning, ending, and separating commas of JSON responses are properly positioned.

**Comment by xenatisch** [comment]
@melvinio16 / @colic001 I have now deployed the new version. Please do give it a go and let me know how if it's made things better or worse.
