### ISSUE TITLE
Queries from archives not returning data

### ISSUE THREAD

**Issue by DaveJephson** [publichealthengland/coronavirus-dashboard-api-v2-server#6]
There is a problem getting data from the archive that seems to be specific to 2021-02-24 and 2021-02-25.

This query returns a blank file:
https://api.coronavirus.data.gov.uk/v2/data?areaType=overview&metric=newDeaths28DaysByDeathDate&format=csv&release=2021-02-24

This query returns a 500 error:
https://api.coronavirus.data.gov.uk/v2/data?areaType=overview&metric=newDeaths28DaysByDeathDate&format=csv&release=2021-02-25

**Comment by xenatisch** [comment]
This was a database-related issue which has now been resolved.
